spring:
  application:
    name: mybatis
  datasource:
  # druid配置：https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      url: jdbc:mysql://192.168.114.3:3306/lawyer?useUnicode=true&characterEncoding=utf8&autoReconnect=true
      username: admin
      password: admin
      driver-class-name:
      initial-size:
      max-active:
      min-idle:
      max-wait:
      pool-prepared-statements:
      max-pool-prepared-statement-per-connection-size:
      validation-query:
      validation-query-timeout:
      test-on-borrow:
      test-on-return:
      test-while-idle:
      time-between-eviction-runs-millis:
      min-evictable-idle-time-millis:
      max-evictable-idle-time-millis:
      filters: stat,wall

# mybatis相关配置参考 http://www.mybatis.org/mybatis-3/configuration.html#settings
mybatis:
  # mybatis xml配置文件的路径
  # config-location:
  # 扫描别名包
  type-aliases-package: ml.study.model
  # 类型处理器
  type-handlers-package:
  configuration:
    # map 类型的列转换为驼峰类型的，比如A_COLUMN -> aColumn
    map-underscore-to-camel-case: true
    # 设置数据库驱动每次查询的大小
    default-fetch-size: 100
    # 设置sql语句执行超时时间
    default-statement-timeout: 30
  # mapper 文件地址
  mapper-locations:
  # 是否检查 xml配置文件
  check-config-location: false



# Mybatis分页插件：https://github.com/pagehelper/Mybatis-PageHelper
# Mybatis分页插件集成spring boot：https://github.com/pagehelper/pagehelper-spring-boot
# PageHelper参数解释： https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/en/HowToUse.md
pagehelper:
  # pagehelper可以自己推断方言，通过这个配置参数也可以指定方言
  helperDialect: mysql
  # 传递的分页参数不合理时，可以对参数进行纠正，如分页参数小于0，则查询第一页，大于最大页，则查询最后一页
  reasonable: true
  # 是否支持mapper里面的接口传递分页参数
  supportMethodsArguments: true
  params: count=countSql
  # 自动检测方言
  auto-dialect: false

# https://github.com/abel533/Mapper/wiki/1.3-spring-boot
mapper:
  mappers: ml.study.mapper.MyMapper









